language: objective-c
osx_image: xcode8.3
branches:
    only:
    - master
env:
    global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=SwiftSky.xcworkspace
    - IOS_FRAMEWORK_SCHEME="SwiftSky iOS"
    - MACOS_FRAMEWORK_SCHEME="SwiftSky macOS"
    - TVOS_FRAMEWORK_SCHEME="SwiftSky tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="SwiftSky watchOS"
    - IOS_SDK=iphonesimulator10.3
    - MACOS_SDK=macosx10.12
    - TVOS_SDK=appletvsimulator10.2
    - WATCHOS_SDK=watchsimulator3.2
    matrix:
        - DESTINATION="OS=10.3,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="YES"    CODE_COVERAGE="YES"
        - DESTINATION="OS=10.2,name=iPhone 7"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=10.1,name=iPhone 6s Plus"    SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=10.0,name=iPhone 6s"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=9.3,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=9.2,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=9.1,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=8.4,name=iPhone 5s"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=8.3,name=iPhone 5s"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=8.1,name=iPhone 4s"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"

        - DESTINATION="arch=x86_64"                    SCHEME="$MACOS_FRAMEWORK_SCHEME"   SDK="$MACOS_SDK"   RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"

        - DESTINATION="OS=10.2,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=10.1,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=10.0,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=9.1,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=9.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  POD_LINT="NO"     CODE_COVERAGE="NO"

        - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"   POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=2.1,name=Apple Watch - 38mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"   POD_LINT="NO"     CODE_COVERAGE="NO"
        - DESTINATION="OS=2.0,name=Apple Watch - 38mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"   POD_LINT="NO"     CODE_COVERAGE="NO"
before_install: rvm use $RVM_RUBY_VERSION
install: gem install cocoapods slather --pre --no-rdoc --no-ri --no-document --quiet
script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - if [ $RUN_TESTS == "YES" ]; then
        travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
      else
        travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
      fi
    - if [ $POD_LINT == "YES" ]; then
        pod lib lint;
      fi
after_success:
    - if [ $CODE_COVERAGE == "YES" ]; then
        bash <(curl -s https://codecov.io/bash) -f coverage/cobertura.xml -X coveragepy -X gcov -X xcode;
      fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b183da5adeaab3d35b8c
    on_success: change
    on_failure: always
    on_start: never
